name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.22
      YAEGI_VERSION: v0.16.1
      CGO_ENABLED: 0
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: go/src/github.com/${{ github.repository }}
          fetch-depth: 0

      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      - name: Setup GOPATH
        run: go env -w GOPATH=${{ github.workspace }}/go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Test
        run: go test -v -cover ./...

      - name: Run tests with Yaegi
        run: yaegi test -v .
        env:
          GO PATH: ${{ github.workspace }}/go
